### ISSUE TITLE
Tastatur i "Logg inn med passord" burde være kun numerisk istedenfor full qwerty

### ISSUE THREAD

**Issue by johnksv** [digipost/android#15]
Når man velger "Logg inn med passord" burde tastaturet være kun numerisk for fødselsnummer.
Dette må vel endres på den underliggende  siden appen kun viser et WebView.
(Ser at dette også er det samme på desktop-utgaven https://www.digipost.no/app/ )

![digipost_password_login_screen](https://cloud.githubusercontent.com/assets/10381866/25196137/003ae406-2540-11e7-8f56-2f4b01e1ebd3.png)

**Comment by ftlno** [comment]
Hei @johnksv ! Så kult at du viser interesse for appen. ja, dette er vi klar over, men er nok kun én av mange småforbedringer som ikke har blitt prioritert enda dessverre. Takk for tipset! og for at du gjør oss bedre! :)
