### ISSUE TITLE
Brev som skal signeres viser kun blank side

### ISSUE THREAD

**Issue by zrrrzzt** [digipost/android#26]
Dersom man mottar et brev som skal signeres vises kun en blank side i android-appen.
Appen for iOS og webappen for digipost viser tekst og link videre til signeringsportalen.

**Comment by ftlno** [comment]
Fikk prioritert inn denne i ettermiddag @zrrrzzt Takk igjen for issue! :) 
Rettet og sendes inn til Google så fort som mulig https://github.com/digipost/android/pull/27

Btw Vi er glade i PRs om det skulle være noe :)
